Make Django 1.5 a hard requirement.
Because of various deprecation issues with Django coding conventions, errors like the following are occurring.
```
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/www/majhar/venv/lib/python3.4/site-packages/django_evercookie/urls.py", line 4, in <module>
    from django.conf.urls.defaults import url, patterns
ImportError: No module named 'django.conf.urls.defaults
```
Will keep Django at 1.5.x as tested and later attempt to rework code as needed for future compat with current stable releases as of the time of this writing (Django 1.10.x).